apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashr
spec:
  selector:
    matchLabels:
      app: crashr
  replicas: 1
  template:
    metadata:
      labels:
        app: crashr
    spec:
      containers:
      - name: crashr
        image: nodesocket/crashr:latest
